### ISSUE TITLE
Error stack trace

### ISSUE THREAD

**Issue by openkwaky** [xamoom/Morpheus#4]
I got a lot of errors/warnings when using the lib.
This doesn't make the app crash, but it is annoying to see it in logcat:

`````` log
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err: org.json.JSONException: No value for attributes
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at org.json.JSONObject.getJSONObject(JSONObject.java:609)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Factory.newObjectFromJSONObject(Factory.java:42)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Mapper.mapRelations(Mapper.java:168)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Factory.newObjectFromJSONObject(Factory.java:49)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Factory.newObjectFromJSONArray(Factory.java:90)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Morpheus.parseFromJSONObject(Morpheus.java:69)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at at.rags.morpheus.Morpheus.parse(Morpheus.java:48)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at com.radiofrance.fipandroid.fragment.TracksByRadioFragment.loadSongsFromBdd(TracksByRadioFragment.java:190)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at com.radiofrance.fipandroid.fragment.TracksByRadioFragment.loadSongs(TracksByRadioFragment.java:121)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at com.radiofrance.fipandroid.fragment.TracksByRadioFragment_.access$201(TracksByRadioFragment_.java:25)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at com.radiofrance.fipandroid.fragment.TracksByRadioFragment_$3.execute(TracksByRadioFragment_.java:121)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-25 13:24:29.968 16678-16902/com.radiofrance.fipandroid W/System.err:     at java.lang.Thread.run(Thread.java:818)```
``````

**Comment by xamoom-raphael** [comment]
Yes you are right. ATM i give out the whole exception, because I have not implemented a good logging structure.

You can deactivate it with:

``` java
Logger.setDebug(false);
```

**Comment by xamoom-raphael** [comment]
Solved in https://github.com/xamoom/Morpheus/commit/44e0353ff24e4a38ce2133f3ea5428a4fc08b9c9 duplicate #8
